### ISSUE TITLE
r1266 won't build on Linux Ubuntu 10.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Heeks/heekscad#300]
```
What steps will reproduce the problem?
1.make clean
2.make

I get this error:
Sketch.cpp: In member function ‘bool CSketch::FilletAtPoint(const gp_Pnt&, 
double)’:
Sketch.cpp:1061: warning: statement has no effect
Sketch.cpp:1065: error: expected unqualified-id before ‘int’
Sketch.cpp:1065: error: expected ‘)’ before ‘int’
make: *** [Sketch.o] Error 1
make: *** Waiting for unfinished jobs....


```

Original issue reported on code.google.com by `ddfalck2...@yahoo.com` on 8 Aug 2010 at 1:22
